# Generated by Django 4.2 on 2023-05-11 13:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "room_no",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Room No",
                    ),
                ),
                (
                    "room_type",
                    models.TextField(
                        choices=[
                            ("Premium", "Premium"),
                            ("Classic", "Classic"),
                            ("Cottage", "Cottage"),
                        ],
                        default="Classic",
                        max_length=30,
                    ),
                ),
                ("room_price", models.IntegerField(default=0)),
                ("room_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booked_from",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Check In Date"
                    ),
                ),
                (
                    "booked_till",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Check Out Date"
                    ),
                ),
                (
                    "reservation_amount",
                    models.FloatField(default=0, verbose_name="Amount Paid"),
                ),
                (
                    "reservation_status",
                    models.CharField(
                        default="Reserved",
                        max_length=254,
                        verbose_name="Reservation Status",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        default="Pending", max_length=254, verbose_name="Payment Status"
                    ),
                ),
                (
                    "provider_order_id",
                    models.CharField(
                        default="", max_length=40, verbose_name="Order ID"
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        default="", max_length=36, verbose_name="Payment ID"
                    ),
                ),
                (
                    "signature_id",
                    models.CharField(
                        default="", max_length=128, verbose_name="Signature ID"
                    ),
                ),
                (
                    "booked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booked_room",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rooms.rooms",
                    ),
                ),
            ],
        ),
    ]
