# Generated by Django 4.2 on 2023-05-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rooms", name="room_price", field=models.FloatField(default=0),
        ),
    ]
